export const CATEGORIES_FETCHING = 'CATEGORIES_FETCHING';
export const CATEGORIES_RECEIVED = 'CATEGORIES_RECEIVED';
export const CATEGORIES_FETCH_ERROR = 'CATEGORIES_FETCH_ERROR';

export const NAVIGATED = 'NAVIGATED';

export const LAUREATES_FETCHING = 'LAUREATES_FETCHING';
export const LAUREATES_RECEIVED = 'LAUREATES_RECEIVED';
export const LAUREATES_FETCH_ERROR = 'LAUREATES_FETCH_ERROR';
